/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        "./App.{js,jsx,ts,tsx}",
        "./app/**/*.{js,jsx,ts,tsx}",
        "./src/**/*.{js,jsx,ts,tsx}"
    ],
    theme: {
        extend: {
            colors: {
                "surface-container": "#eceef0",
                "error-container": "#ffdad6",
                "outline": "#737686",
                "on-primary-fixed-variant": "#003ea8",
                "primary": "#004ac6",
                "on-error": "#ffffff",
                "on-primary-container": "#eeefff",
                "on-secondary-fixed-variant": "#3f465c",
                "surface-variant": "#e0e3e5",
                "on-surface": "#191c1e",
                "inverse-on-surface": "#eff1f3",
                "tertiary-fixed": "#d3e4fe",
                "on-tertiary-fixed": "#0b1c30",
                "surface-container-high": "#e6e8ea",
                "primary-fixed-dim": "#b4c5ff",
                "on-primary": "#ffffff",
                "surface-dim": "#d8dadc",
                "on-tertiary-fixed-variant": "#38485d",
                "error": "#ba1a1a",
                "tertiary": "#46566c",
                "on-secondary-container": "#5c647a",
                "background": "#f7f9fb",
                "secondary": "#565e74",
                "on-secondary-fixed": "#131b2e",
                "surface-bright": "#f7f9fb",
                "surface-container-highest": "#e0e3e5",
                "tertiary-fixed-dim": "#b7c8e1",
                "secondary-fixed": "#dae2fd",
                "on-primary-fixed": "#00174b",
                "on-background": "#191c1e",
                "primary-fixed": "#dbe1ff",
                "primary-container": "#2563eb",
                "inverse-primary": "#b4c5ff",
                "surface-container-low": "#f2f4f6",
                "on-tertiary-container": "#e9f0ff",
                "secondary-fixed-dim": "#bec6e0",
                "on-error-container": "#93000a",
                "on-tertiary": "#ffffff",
                "surface-container-lowest": "#ffffff",
                "on-surface-variant": "#434655",
                "on-secondary": "#ffffff",
                "inverse-surface": "#2d3133",
                "tertiary-container": "#5e6e85",
                "secondary-container": "#dae2fd",
                "outline-variant": "#c3c6d7",
                "surface": "#f7f9fb",
                "surface-tint": "#0053db"
            }
        },
    },
    plugins: [],
}
